= Examination Regulations and Critiria for the https://isaqb.org[iSAQB]^®^ CPSA^®^ Expert Level

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Status
image:https://github.com/isaqb-org/examination-expert/workflows/CI%20-%20Releases%20and%20Main/badge.svg?branch=main["CI – Releases and Main"]
image:https://img.shields.io/github/last-commit/isaqb-org/examination-expert/main.svg["Last commit"]
image:https://img.shields.io/github/contributors/isaqb-org/examination-expert.svg["Contributors",link="https://github.com/isaqb-org/examination-expert/graphs/contributors"]
image:https://img.shields.io/github/issues/isaqb-org/examination-expert.svg["Issues",link="https://github.com/isaqb-org/examination-expert/issues"]
image:https://img.shields.io/github/issues-closed/isaqb-org/examination-expert.svg["Issues closed",link="https://github.com/isaqb-org/examination-expert/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+"]

This is <<copyrighted,copyrighted work>>.

== Content
This repository contains the examination regulations and criteria for the iSAQB^®^ CPSA^®^ Expert Level in AsciiDoc.

== How to clone the project
The project uses Git Modules. So, don't forget to clone the repository with the option --recursive.

If you forgot the option --recursive, you can load the Git Modules with this command
[source,console]
$ git submodule update --init

== How to contribute or participate
Create an issue, a merge- or pull-request

== How to build the documents
Prerequisite: You need Docker installed. The toolchain itself lives in the prebuilt
`ghcr.io/isaqb-org/curriculum-builder` image, so nothing else has to be set up locally.

[source,console]
----
$ ./curriculum-build.sh          # Linux/macOS
> curriculum-build.bat           # Windows
----

That renders both documents – the examination regulations and the criteria – as PDF and
HTML in German (DE) _and_ English (EN) into `build/`.

This repository has two AsciiDoc root documents, `docs/examination-regulations.adoc` and
`docs/examination-criteria.adoc`. The builder image renders exactly one root per run, so
the wrapper scripts read the list from `build.config` and invoke the image once per
document:

[source,sh]
----
: "${CURRICULUM_FILES:=examination-regulations examination-criteria}"
----

Everything else (languages, suffix tags, print layout) is shared between the two
documents and configured in the same `build.config`.

To narrow a build down, pass a format and language, and/or pick a single document:

[source,console]
----
$ ./curriculum-build.sh pdf DE                                # both documents, PDF/German only
$ CURRICULUM_FILE=examination-criteria ./curriculum-build.sh   # criteria only
$ ./curriculum-build.sh clean                                 # remove build/ outputs
----

== Additional translations/languages
include::templates/EXTERNAL_DOCUMENTS_README.adoc[]

== Maintainers

This repository is currently maintained by the Examination Level Working Group
It was forked from https://github.com/isaqb-org/advanced-template.

[[copyrighted]]
== Licensing and Copyright

include::license-copyright/LICENSE.adoc[]
