// tag::DE[]
=== Ziel und Zweck
Beim CPSA-E tragen Sie mit anderen Bewerber:innen Erfahrungswissen aus Ihrer Projektarbeit zusammen.
Gemeinsam ergänzen Sie dieses durch zusätzliches Expert:innenwissen, Recherchen und Austausch miteinander.
Anschließend stellen Sie im Rahmen des CPSA-E dieses Wissen durch Veröffentlichungen vor.
Somit tragen Sie aktiv dazu bei, dass Expert:innenwissen in die Breite getragen wird und sich die Softwarequalität durch Ihren Beitrag auch in anderen Projekten verbessert.
Die Themen dazu wurden vorher über die Website des iSAQB eingereicht.
Nach einer Freigabe durch den/die Themenverwalter:in stehen die Themen zur Bearbeitung zur Verfügung.

==== Ziele
- Sie zeigen, dass Sie in einem Fachgebiet der Softwarearchitektur Expert:in sind.
- Sie erarbeiten mit anderen Expert:innen neues Wissen.
- Sie zeigen Teamfähigkeit.
- Sie tauschen sich mit anderen Expert:innen aus und bauen sich so ein Netzwerk für Ihre
berufliche Zukunft auf.
- Sie präsentieren die Ergebnisse bei Konferenzen oder publizieren in Fachmagazinen.

// end::DE[]

// tag::EN[]
=== Purpose and Intent
During the CPSA-E, you and other candidates bring together experience-based knowledge from your project work. Together, you supplement this with additional expert knowledge, research, and a discussion between yourselves. You then present this knowledge via publications within the scope of the CPSA-E. You thus actively help to disseminate expert knowledge and improve software quality through your contribution, even in other projects.

The topics were submitted in advance via the iSAQB website. Following approval by the topic admin-
istrator, the topics are available to be worked on.

=== Objectives:
-  You show that you are an expert in a specialist field of software architecture.
- You develop new knowledge with other experts.
- You show the ability to work in a team.
- You interact with other experts, thereby building a network for your professional future.
- You present the results at conferences or publish them in trade magazines.

// end::EN[]

