// tag::DE[]
=== Voraussetzungen

Das CPSA Expert Level (CPSA-E) ist die höchste Qualifizierungsstufe des iSAQB und richtet sich an äußerst erfahrene Softwarearchitekt:innen. Die Anforderungen und Voraussetzungen sind entsprechend anspruchsvoll und fokussieren sich auf fundierte Erfahrung, tiefgehende Expertise sowie die Fähigkeit, neue Lösungswege zu entwickeln und die Community zu bereichern.

Eine Bewerber:in muss erfolgreich die iSAQB-Advanced Level-Zertifizierung erlangt haben. Eine Mindestzeit zwischen Advanced- und Expert Level-Zertifizierung wird nicht gefordert.

Das Thema der Expert Level-Zertifizierung muss inhaltlich zu Spezialisierung passen, die ein:e Bewerber:in im Rahmen der Advanced Level-Zertifizierung gewählt hat.

Eine Bewerber:in muss langjährige Projekterfahrung in der Softwarearchitektur haben und tiefgreifendes Wissen im Bereich des gewählten Themas haben.

// end::DE[]

// tag::EN[]

=== Preconditions

The CPSA Expert Level (CPSA-E) is the highest qualification level awarded by the iSAQB. It targets highly skilled and experienced software architects. Applicants must meet demanding requirements: long-term experience, a clear area of expertise, the ability to develop innovative approaches and solutions, and active contributions to the professional community.

Applicants must have successfully obtained the iSAQB Advanced Level certification. There is no minimum time requirement between obtaining the Advanced Level and Expert Level certifications.

The topic of the Expert Level certification must align with the specialization the applicant selected as part of the Advanced Level certification.

Applicants must have many years of project experience in software architecture and in-depth knowledge of the chosen topic.

// end::EN[]

