// tag::DE[]
=== Prüfungsvoraussetzungen

Ein:e Expert-Level-Bewerber:in muss als Eignungsvoraussetzung erfolgreich die iSAQB-Advanced-Level-Zertifizierung erlangt haben.
Ansonsten gibt es keine Eignungsvoraussetzungen.
Sie sollten jedoch langjährige Projekterfahrung und tiefgreifendes Wissen im Bereich Ihres gewählten Softwarearchitekturthemas haben, das Sie mit der Themenarbeitsgruppe bearbeiten möchten.
Die Praxiserfahrung muss nicht nachgewiesen werden, da sie schon Voraussetzung für die iSAQB- Foundation- und Advanced-Level-Zertifizierungen ist. Auch eine Mindestzeit zwischen Advanced- und Expert-Level-Zertifizierung wird nicht gefordert.

// end::DE[]

// tag::EN[]
=== Preconditions
As a qualification requirement, an Expert Level candidate must have successfully acquired the iSAQB Advanced-Level certification. There are no other qualification requirements. However, you should have extensive project experience and in-depth knowledge in the field of your chosen software architecture
topic, which you would like to work on with the topic working group.

The practical experience does not need to be proven as it is already a requirement for the iSAQB Foundation and Advanced-Level certifications. There is also no minimum amount of time that must have passed between the Advanced and the Expert Level certification.

// end::EN[]

