// tag::DE[]
=== Kosten

Die Kosten für die Zertifizierung werden durch den Zertifizierer und die Trainingsanbieter pro Leistung separat in Rechnung gestellt. Dadurch wird sichergestellt, dass Themenbearbeiter Seminare bei unterschiedlichen Trainingsanbietern besuchen können. Falls sich jemand dafür entscheidet, den Zertifizierungsprozess nicht zu beenden, fallen nur Kosten für bereits erbrachte Leistungen an.

Die folgende Liste zeigt, welche Leistungserbringer welche Kosten in Rechnung stellen:

* Zertifizierer:
** Prüfung der Voraussetzungen
** Verbesserung und Abnahme der Roadmap
** Prüfung der Ergebnisse
** Individuelles Prüfungsgespräch
** Ausstellung des Zertifikats

* Trainingsanbieter:
** Teilnahme an Seminaren (mindestens 2)


// end::DE[]

// tag::EN[]
=== Costs

Certification costs are billed separately by the certifying body and the training providers for each service. This ensures topic workers can attend seminars from different training providers. Applicants who fail to finish the certification process will only be charged for services that have already been rendered.

The following list shows which services are billed:

* Certifying body:
** Verification of the prerequisites
** Improvement and acceptance of the roadmap
** Review of the results
** Individual certification interview
** Issuance of the certificate

* Training providers:
** Participation in seminars (at least 2)

// end::EN[]
