// tag::DE[]
=== Prüfungskosten
Die Kosten für eine Zertifizierung im Expert Level setzen sich aus dem Aufwand für den/die gewählte:n Themenmoderator:in und die Zertifizierungsstelle zusammen.
Die Preise können je nach Gruppengröße schwanken.
Ungefähre Kostenschätzung für die gesamte Themenarbeitsgruppe:

- Kosten für Zertifizierungsstelle: 2600,- €
- Kosten für Themenmoderator:in: circa 8000,- € (Angebote der für das EL akkreditierten
Trainingsprovider können unterschiedlich ausfallen)
- Eventuell zusätzlich anfallende Kosten, z.{nbsp}B. für Reisen im Rahmen der Zusammenarbeit
oder Extrakosten durch Nachbesserungen, sind nicht inkludiert und selbstorganisatorisch von der Themenarbeitsgruppe zu tragen.

// end::DE[]

// tag::EN[]
=== Examination Costs
The costs of certification at the Expert Level comprise the costs for the selected topic moderator and the certification body. The prices can vary depending on the size of the group. Rough cost estimate for the whole topic working group:

- Costs for certification body: € 2600
- Costs for the topic moderator: approx. € 8000 (quotations for the training providers accredited for the EL can vary)
- Possible additional costs, e.g., for travel within the scope of the collaboration or extra costs due to corrections are not included and are to be borne by the topic working group itself.



// end::EN[]
