// tag::DE[]
=== Schritt 3: Zertifizierer und Trainingsprovider beauftragen

Die Themenarbeitsgruppe muss einen Zertifizierer und einen Trainingsprovider auswählen. Der Trainingsprovider stellt eine:n Themenmoderator:in bereit, der die Themenarbeitsgruppe durch den gesamten Arbeitsprozess begleitet und unterstützt.

Das ist der Prozess:

1. iSAQB listet auf ihrer Internetseite die akkreditierten Zertifizierer und Trainingsprovider auf.
2. Die Themenarbeitsgruppe wählt einen Trainingsprovider aus.
3. Die Themenarbeitsgruppe kontaktiert einen Zertifizierer.
4. Jede Person der Themenarbeitsgruppe schließt mit dem Zertifizierer einen Vertrag ab.
5. Der Zertifizierer schließt einen Vertrag mit dem Trainingsprovider ab.
6. Die Themenarbeitsgruppe kann mit der Arbeit beginnen.

// end::DE[]

// tag::EN[]
=== Step 3: Contract Certifying Body and Training Provider

The topic working group must choose a certifying body and a training provider body before it can start working. The training provider makes a topic moderator available. This topic moderator guides the topic working group through the entire working process and approves working steps.

This is the process:

1. iSAQB lists all accredited certification bodies and training providers on its website.
2. The topic working group chooses a training provider.
3. The topic working group contacts a certifying body.
4. Each member of the working group concludes a contract with the certifying body.
5. The certifying body concludes a contract with the training provider.
6. The topic working group can start working.


// end::EN[]
