// tag::DE[]
=== Schritt 4: Roadmap erstellen
Die Themenarbeitsgruppe erstellt eine Roadmap, in der sie inhaltlich und zeitlich ihren Plan für ihr Vorgehen verschriftlicht.
Der/die Themenmoderator:in kann hierbei unterstützen.
Schließlich wird die Roadmap bei dem/der Themenmoderator:in eingereicht, welche:r diese anhand festgelegter Kriterien überprüft.

include::../05-criteria/05-criteria-roadmap.adoc[{include_configuration}]

Gibt der/die Themenmoderator:in die Roadmap frei, kann die Themenarbeitsgruppe mit der Umsetzung beginnen.
Bei Ablehnung der Roadmap hat die Themenarbeitsgruppe einen weiteren Versuch, die Roadmap zu verbessern und erneut abzugeben.

// end::DE[]

// tag::EN[]
=== Step 4: Create Roadmap
The topic working group creates a roadmap, in which they put down in writing their plan for their procedure in terms of content and timescale. The topic moderator can provide assistance here. The roadmap is ultimately submitted to the topic moderator, who assesses this based on specified criteria.

include::../05-criteria/05-criteria-roadmap.adoc[{include_configuration}]

If the topic moderator approves the roadmap, the topic working group can begin with implementation. If the roadmap is rejected, the topic working group has one further attempt to improve and re-submit the roadmap.


// end::EN[]
