// tag::DE[]
=== Schritt 4: Roadmap erstellen

Der/die Themenbearbeiter:in beziehungsweise die Themenarbeitsgruppe erstellt eine Roadmap, in der sie inhaltlich und zeitlich ihren Plan für ihr Vorgehen verschriftlichen. 


include::../05-criteria/05-criteria-roadmap.adoc[{include_configuration}]

Der/die Themenbearbeiter oder die Themenarbeitsgruppe reicht die Roadmap beim Zertifizierer ein, welcher sie an die Prüfer weiterleitet. Diese überprüfen, ob die in der Roadmap beschriebenen Arbeitsergebnisse verständlich, ausreichend beschrieben sowie messbar sind. Die Prüfer:innen ergänzen gegebenenfalls die Roadmap.

Sollten die Prüfer:innen mit der Roadmap nicht zufrieden sein, kann der/die Themenbearbeiter:in oder die Themenarbeitsgruppe die Roadmap einmalig nachbessern.

Erst wenn die Prüfer:innen die Roadmap freigegeben haben, kann der/die Themenbearbeiter:in bzw. die Themenarbeitsgruppe mit der Arbeit beginnen.

// end::DE[]

// tag::EN[]
=== Step 4: Create Roadmap
The topic worker or the topic working group creates a roadmap in which they set out their plan for how to proceed, including both content and timelines.


include::../05-criteria/05-criteria-roadmap.adoc[{include_configuration}]

The topic worker or the topic working group submits the roadmap to the certifying body, which forwards it to the examiner. The examiner verify whether the deliverables described in the roadmap are clearly and sufficiently defined and measurable. If necessary, the reviewers make additions to the roadmap.

If the examinters are not satisfied with the roadmap, the topic worker or topic working group revise the roadmap once.

The topic worker or topic working group can only start working after the examiners have approved the roadmap.

// end::EN[]
