// tag::DE[]
=== Übersicht
Die Zertifizierung erfolgt in diesen Schritten:

1. Der/die Themenbearbeiter:in beziehungsweise die Themenarbeitsgruppe stellt sicher, dass die Ziele der Roadmap erreicht wurden und die Ergebnisse die formellen Kriterien erfüllen.
2. Der/die Themenbearbeiter:in beziehungsweise die Themenarbeitsgruppe reicht die Ergebnisse beim Zertifizierer ein, welcher diese ebenfalls auf die formellen Kriterien prüft.
3. Zwei Prüfer:innen bewerten die Ergebnisse inhaltlich. Der/die Themenbearbeiter:in beziehungsweise die Themenarbeitsgruppe kann einmalig nachbessern. Nur wenn die Prüfer:innen die Ergebnisse positiv bewerten, darf der/die Themenbearbeiter:in beziehungsweise dürfen die Mitglieder der Themenarbeitsgruppe am individuellen Prüfungsgespräch teilnehmen.
4. Zwei Prüfer:innen führen ein individuelles Prüfungsgespräch durch. Da Zertifikate individuell ausgestellt werden, hängt das Ergebnis bei einer Zertifizierung von Mitgliedern von Themenarbeitsgruppen allein vom individuellen Prüfungsgespräch ab.
5. Der Zertifizierer stellt die Zertifikate aus.

Die gesamte Zertifizierung soll in sechs Wochen abgeschlossen sein (ohne Nachbesserung und Einspruch).

Die Details zu den Schritten werden in den folgenden Abschnitten beschrieben.

// end::DE[]

// tag::EN[]
=== Overview
The certification process consists of the following steps:

1. The topic worker or topic working group verifies that the roadmap's objectives have been achieved and that the results meet the formal criteria.
2. The topic worker or topic working group submits the results to the certifying body, which checks them for compliance with the formal criteria.
3. Two examiners evaluate the results based on the content criteria. The topic worker or topic working group may improve the results once. The topic worker or the members of the topic working group can participate in the individual examination interview if the examiners evaluate the results positively.
4. Two examiners conduct an individual examination interview. Since certificates are issued individually, the outcome of certification for members of topic working groups depends solely on the individual examination interview.
5. The certifying body issues the certificates.

The entire certification process must be completed within six weeks, excluding rework and appeals.

The following sections provide a more thorough description of the steps.

// end::EN[]