// tag::DE[]
=== Übersicht
Die Zertifizierung erfolgt in diesen Schritten:

1. Der/die Themenmoderator:in stellt sicher, dass die Ergebnisse der Themenarbeitsgruppe formelle Kriterien erfüllen.
2. Zwei Prüfer:innen bewerten die Ergebnisse der Themenarbeitsgruppe inhaltlich. Die Themenarbeitsgruppe kann eimmalig nachbessern. Nur wenn die Prüfer:innen die Ergebnisse der Themenarbeitsgruppe positiv bewerten, dürfen die Mitglieder der Themenarbeitsgruppe am individuellen Prüfungsgespräch teilnehmen.
3. Zwei Prüfer:innen führen mit jedem Mitglied der Themenarbeitsgruppe ein Prüfungsgespräch durch. Da Zertifikate individuell ausgestellt werden, hängt das Ergebnis einer Zertifizierung alleinig vom individuellen Prüfungsgespräch ab.
4. Der Zertifizierer stellt die Zertifikate aus.

Die gesamte Zertifizierung soll in sechs Wochen abgeschlossen (ohne Nachbesserugn und Einspruch).

Die Details zu den Schritten werden in den folgenden Abschnitten beschrieben.

// end::DE[]

// tag::EN[]
=== Overview
The certification process consists of the following steps:

1. The topic moderator verifies that the results of the topic working group meet formal criteria.
2. Two examiners evaluate the results according to the content criteria. The topic working group can improve the results once. Only if the examiners approve the topic working group's results can its members join the individual exam interview.
3. Two examiners conduct individual verbal exams with each topic working group member. As certificates are issued individually, the result of the certification depends solely on the individual verbal exam.
4. The certifying body issues the certificates.

The entire certification process should be completed within six weeks, excluding rework and appeals.

The following sections provide a more thorough description of the steps.
// end::EN[]