// tag::DE[]
=== Abgabe
Ist die Roadmap erfüllt, gibt die Themenarbeitsgruppe ihre Ergebnisse bei dem/der Themenmoderator:in ab.
Er/sie prüft die Ergebnisse auf formelle Kriterien und fordert gegebenenfalls noch Nachbesserungen ein.

==== Formelle Kriterien
[cols="<3,<1,<7a"]
|===
| Kriterium | Pflicht | Beschreibung

| Artikel
| Muss
| Hat der Artikel die folgende Struktur und folgenden Inhalt?

1. Titel
  a. Passt der Titel zum behandelten Thema?
2. Autor:innen
  a. Sind die Autor:innen namentlich angeführt?
  b. Sind die E-Mail-Adressen der Autor:innen aufgelistet?
3. Abstract
  a. Wird die Problemstellung kurz beschrieben?
  b. Beschreibt das Abstract die Hauptthesen oder Ergebnisse?
  c. Ist die Beschreibung kurz und verständlich?
4. Einleitung
  a. Beschreibt die Einleitung den derzeitigen Wissensstand?
  b. Wird die Motivation behandelt?
  c. Wird beschrieben, welche Wissenslücken es gibt, die durch diesen wissenschaftlichen Artikel gefüllt werden sollen?
  d. Werden die Fragestellungen beschrieben, die im Artikel beantwortet werden sollen?

|
|
| 5. Hauptteil (Kapitelname(n) sind frei wählbar)
  a. Materialien und Methoden
    - Werden die Informationsquellen beschrieben?
    - Werden die Methoden beschrieben, die zur Beantwortung der Fragestellung zum Einsatz kamen?
  b. Resultate
    - Werden die Erkenntnisse beschrieben?
    - Werden die Erkenntnisse mit ausreichend plausiblen Daten begründet?
  c. Diskussion
    - Wird beschrieben, wie die Erkenntnisse interpretiert werden?
    - Werden Fragen behandelt, welche sich aus den Ergebnissen ergeben?
    - Wird behandelt, welche Auswirkun- gen die Erkenntnisse auf die Praxis haben?
6. Zusammenfassung
  a. Werden alle Fragestellungen und deren Beantwortung kurz zusammengefasst?
  b. Werden die Auswirkungen der Erkenntnisse kurz behandelt?
7. Danksagung
  a. Werden Unterstützer:innen angeführt?
8. Interessenskonflikte
  a. Werden Interessenskonflikte angeführt?
9. Literaturliste
  a. Wird die gesamte verwendete Literatur aufgelistet?
  b. Wird korrekt zitiert?

| Weiteres Ergebnis
| Muss
| - Erfüllen Form und Inhalt den Zweck des Ergebnisses (z. B. ein neues Muster nach der Mustersprache Kon- text, Problem, Lösung)?
- Ist das Ergebnis verständlich beschrieben?
- Ist ersichtlich, dass zur Erarbeitung des weiteren Ergebnisses mindestens zwei Personenwochen notwendig waren?

| Einreichungen
| Soll
| - Hat die Themenarbeitsgruppe zumindest bei einer Konferenz einen Vortrag oder einen Workshop ein- gereicht?
- Hat die Themenarbeitsgruppe versucht, die Ergebnisse in zumindest einer Fachzeitschrift zu publizieren?

| Erfahrungsbericht
| Muss
| - Hat jedes Mitglied der Themenarbeitsgruppe einen Erfahrungsbericht abgegeben?
- Sind alle Punkte in den Erfahrungsberichten ausgefüllt?

| Mitarbeit
| Muss
| - Der/die Themenmoderator:in bestätigt, dass sich nach seiner / ihrer Wahrnehmung alle Mitglieder der Themenarbeitsgruppe ungefähr gleich intensiv eingebracht haben.
- Alle Mitglieder der Themenarbeitsgruppe legen jeweils ein Arbeitsprotokoll vor, in dem sie ihre Tätigkeiten protokolliert haben.

|===

// end::DE[]

// tag::EN[]
=== Submit Result


// end::EN[]
