// tag::DE[]
=== Prüfungsleistungen
Zur Zertifizierung muss eine Themenarbeitsgruppe folgende Ergebnisse abgeben:

[cols="<3,<1,<7a"]
|===
| Kriterium | Pflicht | Beschreibung

| Artikel
| Muss
| Der Artikel beschreibt die Ergebnisse der Themenarbeitsgruppe. Das iSAQB stellt eine Vorlage bereit.

| Weiteres Ergebnis
| Muss
| Die Themenarbeitsgruppe muss mindestens ein frei wählbares weiteres Ergebnis ausarbeiten, wie z.{nbsp}B. Anleitungen, Best Practices, Auswertungen von Umfragen.

| Einreichungen
| Soll
| Die Themenarbeitsgruppe soll ihre Ergebnisse auf Konferenzen einreichen oder in Fachzeitschriften publizieren. Zum Nachweis gibt die Themenarbeitsgruppe etwa ein Abstract oder eine Kopie eines veröffentlichten Artikels ab.

| Erfahrungsbericht
| Muss
| Jedes Mitglied einer Themenarbeitsgruppe erstellt einen Erfahrungsbericht, damit das iSAQB die Prozesse weiterentwickeln kann. Das iSAQB stellt dazu eine Vorlage bereit.

|===

Die Themenarbeitsgruppe genehmigt dem iSAQB die Veröffentlichung ihrer Ergebnisse. _Ebenso kann jedes Mitglied der Themenarbeitsgruppe die Ergebnisse unter Angabe der Mitwirkenden und des iSAQB frei verwerten. (Siehe Punkt E.5 der FAQs > Formulierung wird wahrscheinlich nochmal angepasst.)_ Das iSAQB veröffentlicht unter Benennung aller Beteiligten den Artikel auf seinen Seiten und übersetzt diesen in verschiedene Sprachen.

==== Beurteilung
Die gemeinsame Beurteilung der Prüfer:innen erfolgt nach dem folgenden Kriterienkatalog. Es müssen mindestens 20 der 30 Punkte erreicht werden. In jeder Kategorie müssen 4 der 10 Punkte erreicht werden. Für jedes Kriterium können die Prüfer:innen eine Begründung angeben.

include::../05-criteria/07-criteria-content.adoc[{include_configuration}]

Sechs Wochen nachdem die Themenarbeitsgruppe die Ergebnisse eingereicht hat, bekommen die Mitglieder über den Zertifizierer das Ergebnis mitgeteilt:
Erfolgreiche Zertifizierung, Ablehnung oder Nachbesserung nötig.
Die Themenarbeitsgruppe erhält Einblick in die Begründung der Prüfungsergebnisse.


// end::DE[]

// tag::EN[]
=== Examination Components
For certification, a topic working group must submit the following results:

[cols="<3,<1,<7a"]
|===
| Result | Requirement | Description

| Article
| Essential
| The article describes the results of the topic working group.  iSAQB provides a template.

| Additional result
| Essential
| The topic working group must create at least one freely selectable additional result, such as instructions, best practices, and evaluations of surveys.

| Submissions
| Desired
| The topic working group should submit their results to conferences or publish them in trade publications. As evidence, the topic working group submits an abstract or a copy of the published article.

| Experience report
| Essential
| Each member of a topic working group creates an experience report to enable iSAQB to further develop the processes. iSAQB provides a template for this.

|===

The topic working group permits iSAQB to publish their results. Each member of the topic working group can also use the results freely, stating the collaborators and iSAQB. iSAQB publishes the article on its pages, naming all of those involved, and translates it into various languages.


==== Assessment
The joint assessment of the examiners takes place according to the following catalog of criteria. At least 20 of the 30 points must be achieved. 4 out of 10 points must be achieved in each category. The examiners can provide justification for each criterion.

include::../05-criteria/07-criteria-content.adoc[{include_configuration}]

Six weeks after the topic working group has submitted the results, the members are informed of the result by the certifying body: Successful certification, rejection, or correction required. The topic working group gains insight into the justification for the examination results.

// end::EN[]
