// tag::DE[]
=== Formelle Prüfung

Der/die Themenbearbeiter:in beziehungsweise die Themenarbeitsgruppe stellen sicher, dass die Ziele der Roadmap erreicht wurden und die Ergebnisse die formellen Kriterien erfüllen.

Danach können die Ergebnisse beim Zertifizierer eingereicht werden, welcher diese ebenfalls auf folgende formelle Kriterien prüft.

include::../05-criteria/06-criteria-formal.adoc[{include_configuration}]

Der Zertifizierer lässt nur jene Mitglieder zur Zertifizierung zu, welche die Kriterien zur Mitarbeit erfüllt haben. Hat ein Mitglied die Kriterien nicht erfüllt, bekommt er/sie die bisher angefallenen Kosten nicht zurückerstattet.

// end::DE[]

// tag::EN[]
=== Formal Check
The topic worker or the topic working group ensures that the roadmap’s objectives have been met and that the results meet the formal criteria.

The results can then be submitted to the certifying body, which also reviews them against the following formal criteria:

include::../05-criteria/06-criteria-formal.adoc[{include_configuration}]

After the topic moderator approves the results, the topic working group can submit them to the certifying body.

The certifying body only accepts those members for certification who have fulfilled the criteria for participation. If a member fails to meet the criteria, they will not be reimbursed.

// end::EN[]
