// tag::DE[]
=== Inhaltliche Prüfung

==== Bewertung durch zwei Prüfer:innen

Der Zertifizierer beauftragt zwei Prüfer:innen mit der inhaltlichen Beurteilung der Ergebnisse. Die Prüfer:innen bewerten die Ergebnisse anhand der nachfolgenden inhaltlichen Kriterien. 

include::../05-criteria/07-criteria-content.adoc[{include_configuration}]

Es müssen mindestens 20 von 30 Punkten erreicht werden. In jeder Kategorie müssen mindestens 4 von 10 Punkten erreicht werden. Für jedes Kriterium können die Prüfer:innen eine Begründung angeben.

==== Einmalige Nachbesserung

Wenn die Prüfer:innen feststellen, dass die Ergebnisse den Kriterien nicht entsprechen, kann der/die Themenbearbeiter:in beziehungsweise die Themenarbeitsgruppe einmalig nachbessern. Es steht dem Zertifizierer frei, die Zusatzkosten für die Prüfer in Rechnung zu stellen.

// end::DE[]

// tag::EN[]
=== Content Assessment

==== Assessment by Two Examiners

The certifying body appoints two examiners to assess the content of the results. The examiners use the following content criteria to assess the results.

include::../05-criteria/07-criteria-content.adoc[{include_configuration}]

A minimum of 20 out of 30 points must be achieved. At least 4 out of 10 points must be achieved in each category. The examiners can provide justification for each criterion.

==== One-Time Retry

If the examiners find that the results do not meet the criteria, the topic worker or topic working group can improve the results once and submit them again to the certifying body. The certifying body is free to charge for the extra effort.


// end::EN[]
