// tag::DE[]
=== Prüfungsgespräch

Nachdem die Prüfer:innen die Ergebnisse der Themenarbeitsgruppe positiv bewerten haben, laden sie alle Mitglieder der Themenarbeitsgruppe zu einem individuellem Prüfungsgespräch ein. Das Prüfungsgespräch dauert zwischen 30 und 60 Minuten und kann auch online durchgeführt werden. 

In dem Gespräch muss der Prüfling die Ergebnisse verteidigen und sein/ihr Wissen zu diesem Thema unter Beweis stellen.

In der folgenden Tabelle sind der Zeitplan und die Kriterien aufgeführt, die von den Prüfern zur Bewertung verwendet werden:

include::../05-criteria/09-criteria-verbal-exam.adoc[{include_configuration}]

// end::DE[]

// tag::EN[]
=== Oral Exam

If the examiners have assessed the results positively, they invite each member of the topic working group to an individual verbal exam (interview). The verbal exam takes thirty to sixty minutes and can be done online.

The examinee has to defend the results and must show that he/she has sufficient understanding of the topic.

The following table lists the schedule and criteria used by the examiners for evaluation:

include::../05-criteria/09-criteria-verbal-exam.adoc[{include_configuration}]
// end::EN[]