// tag::DE[]
=== Prüfungsgespräch

Falls die Prüfer:innen die Ergebnisse positiv bewertet haben, laden sie den/die Themenbearbeiter:in beziehungsweise alle Mitglieder der Themenarbeitsgruppe zu einem individuellen Prüfungsgespräch ein. Das Prüfungsgespräch dauert zwischen 30 und 60 Minuten und kann auch online durchgeführt werden. 

In dem Gespräch muss der Prüfling die Ergebnisse verteidigen und sein/ihr Wissen zu diesem Thema unter Beweis stellen.

In der folgenden Tabelle sind Zeitplan und Kriterien aufgeführt, die von den Prüfern zur Bewertung verwendet werden:

include::../05-criteria/09-criteria-verbal-exam.adoc[{include_configuration}]

// end::DE[]

// tag::EN[]
=== Oral Exam

If the examiners positively assess the results, they invite the topic worker or each member of the topic working group to an individual verbal exam (interview). The verbal exam lasts between 30 and 60 minutes and may be conducted online.

The examinee must defend the results and demonstrate sufficient understanding of the topic.

The following table lists the schedule and criteria used by the examiners for evaluation:

include::../05-criteria/09-criteria-verbal-exam.adoc[{include_configuration}]
// end::EN[]