// tag::DE[]
=== Einspruch
Themenarbeitsgruppen, deren abgegebene Arbeit die Prüfung nicht besteht, haben das Recht, innerhalb eines Monats nach Bekanntgabe des Ergebnisses einen schriftlichen Einspruch gegen die Bewertung einzulegen.
Der Einspruch muss innerhalb von zwei Monaten nach Bekanntgabe des Ergebnisses schriftlich begründet werden.
Es werden nur sachliche Einwände (z.{nbsp}B. Verstöße gegen die Prüfungsordnung oder sachliche Fehler bei der Bewertung) berücksichtigt.
Einsprüche, die auf Meinungen beruhen, werden abgelehnt.
Die Zertifizierungsstelle prüft die Einhaltung der formalen Anforderungen für die Einreichung und Begründung eines Einspruchs und kann den Einspruch als unzulässig zurückweisen, wenn die Frist für die Einreichung und/oder Begründung des Einspruchs nicht eingehalten wurde.
Wenn alle Anforderungen erfüllt sind, leitet die Zertifizierungsstelle die Beanstandungsgründe an die Prüfer:innen weiter, die den Antrag überprüft haben.
Diese bewerten die Gründe und geben dazu eine schriftliche Stellungnahme ab.
Die Stellungnahme bestätigt die Bewertung oder gibt eine neue Bewertung ab, die endgültig und verbindlich ist und nicht weiter angefochten werden kann.

// end::DE[]

// tag::EN[]
=== Appeal
Topic working groups whose submitted work does not pass the examination have the right to submit a written appeal against the assessment within one month of the announcement of the result. The appeal must be justified in writing within two months of the announcement of the result. Only factual objections (e.g., violations of the examination rules and regulations or objective mistakes during the assessment) are taken into consideration. Appeals based on opinions are rejected. The certification body assesses compliance with the formal requirements for the submission and justification of an appeal and can reject the appeal as inadmissible if the deadline for the submission and/or justification of the appeal has not been observed. If all the requirements are fulfilled, the certification body passes on the grounds for the appeal to the examiners who assessed the application. They assess the grounds and submit a written statement. The statement confirms the assessment or delivers a new assessment, which is final and binding and cannot be contested any further.

// end::EN[]
