// tag::DE[]
=== Zertifikat

==== Ausstellung
Der Zertifizierer informiert die Prüflinge über die Ergebnisse der Zertifizierung. Das Zertifikat erhält jemand, wenn folgende Bedingungen erfüllt sind:

- Die Prüfer:innen haben die Ergebnisse (der Themenarbeitsgruppe) als positiv beurteilt.
- Die Prüfer:innen haben das Prüfungsgespräch mit dem Bewerber als positiv beurteilt.

Das Zertifikat wird für die gewählte Spezialisierung und das bearbeitete Thema. Die Person darf sich als iSAQB-zertifizierte Expert:in für die Spezialisierung bezeichnen.

Personen können mehrere Expert Level-Zertifizierungen erlangen.

Die Gültigkeitsdauer der Expert Level-Zertifizierung ist unbegrenzt.


==== Einspruch
Ein Prüfling kann innerhalb von vier Wochen beim Zertifizierer schriftlich Einspruch gegen die Bewertung erheben.

Der Zertifizierer lost zwei neue Prüfer:innen aus und stellt ihnen die Protokolle zum Prüfungsverfahren und die Ergebnisse der Themenarbeitsgruppe zur Verfügung.

Die Prüfer:innen des Einspruchs bestätigen die Bewertung oder sprechen eine neue Bewertung aus. Das Ergebnis des Einspruchsverfahrens ist nicht mehr anfechtbar.

Geben die Prüfer:innen dem Einspruch statt, kann der Prüfling erneut ein Prüfungsgespräch mit den neuen Prüfer:innen führen. Dafür hebt der Zertifizierer eine Gebühr von 1500 € zzgl. MwSt. ein.

// end::DE[]

// tag::EN[]

=== Certificate

==== Issuing
The certifying body informs the examinees about the results of the certification. The following criteria must be satisfied to receive the certificate:

- The examiners have assessed the results (of the topic working group) as positive.
- The examiners assessed the oral exam as positive.

The certificate is issued for the selected specialization and the topic. The holder may refer to themselves as an iSAQB-certified expert in the field.

Individuals can obtain multiple Expert Level certifications.

The Expert Level certification has no expiration date.

==== Objection

An examinee may object to the assessment within four weeks. The objection must be submitted in writing to the certifying body.

The certifying body selects two new examiners. The certifying body provides the new examiners with access to the assessment protocols and topic working group outcomes.

The new examiners confirm the assessment or issue a new one. The result of the objection procedure is final.

If the examiners issue a new assessment, the examinee may apply for a new oral exam for a fee of €1,500 plus VAT.

// end::EN[]