// tag::DE[]
==== Kriterien für neue Bewerber:innen
Bewerber:innen müssen folgende Kriterien erfüllen, um in einer Themenarbeitsgruppe mitarbeiten zu dürfen:

[cols="<3,<7a"]
|===
| Kriterium | Beschreibung

|Advanced Level
|Bewerber:innen müssen bestätigen, dass sie spätestens bis zur Einreichung der Expert-Level-Arbeit über das Advanced-Level-Zertifikat verfügen.

|Wissen und Praxiserfahrung
|Bewerber:innen begründen ihre Eignung für das Thema, indem sie ihr Wissen und ihre Praxiserfahrung zusammenfassen.


|iSAQB^®^ darf Ergebnisse veröffentlichen und verwerten
|Bewerber:innen müssen einwilligen, dass die Ergebnisse der Themenarbeitsgruppe von iSAQB^®^ veröffentlicht und verwertet werden dürfen.

|Reisebereitschaft
|Bewerber:innen müssen sich bereit erklären, für die Arbeit in der Themenarbeitsgruppe Reisen auf eigene Kosten zu unternehmen.

|Weitergabe von Kontaktdaten
|Bewerber:innen erteilen dem iSAQB^®^ die Berechtigung, folgende Daten an andere Mitglieder der Themenarbeitsgruppe weiterleiten zu dürfen: Vorname, Nachname, E-Mail-Adresse, Telefonnummer.

|===

[NOTE]
.Folgende Kriterien treten vielleicht in Zukunft in Kraft
====
Das iSAQB^®^ kann auch Personen ohne Advanced-Level-Zertifikat als Bewerber:innen für den Expert Level zulassen, wenn sie eine der folgenden Kriterien erfüllen:

- Personen, die als Koryphäe auf dem zu bearbeitenden Thema bekannt sind.
- iSAQB-Mitglieder, die auf Grund ihrer Aufgabe beim iSAQB^®^ die Advanced-Level-Prüfungsfragen (bzw. -aufgaben) kennen und daher die Advanced-Level-Zertifizierung nicht machen können.

Die Entscheidung, ob jemand die obigen Kriterien erfüllt, wird durch einen Mehrheitsbeschluss vom iSAQB Strategie-Council und den Mitgliedern der AG-EL gefällt.

Das iSAQB^®^ kann aktiv Koryphäen einladen, in einer Themenarbeitsgruppe mitzuarbeiten und kann ihnen dafür die Kosten erstatten.

Auch Koryphäen müssen in Themenarbeitsgruppen mitarbeiten. Ohne Mitarbeit in einer Themenarbeitsgruppe und einer erfolgreichen Zertifizierung erhält niemand das EL-Zertifikat.
====

// end::DE[]

// tag::EN[]
==== Criteria for New Applicants
To be eligible to participate in a topic group, applicants must satisfy the following criteria:


[cols="<3,<7a"]
|===
| Criterion | Description

|Advanced Level Certifications
|Applicants must confirm that they have the expert level certification, or they will get it until the topic group submits their results.

|Knowledge and practical experience
|Applicants must prove that they have knowledge and practical experience of the chosen topic.

|iSAQB^®^ can publish results
|Applicants must agree that iSAQB^®^ is allowed to publish and exploit the results of the topic group.

|Willingness to travel
|Applicants must confirm that they are willing to travel at their own expense to work together in the topic group.

|Disclosure of contact data
|The applicants grant permission to iSAQB^®^ to forward the following contact details to the other members of the topic groups: first name, second name, e-mail address, and telephone number.

|===

[NOTE]
.The following criteria may come into operation in the future
====
iSAQB® may accept individuals as candidates for the expert level if they meet one of the following requirement:

- People who are well-known luminaries on the topic.
- Members of iSAQB^®^ who are not permitted to participate in the iSAQB^®^ Advanced Level Certification since they know the examination question.

The iSAQB^®^ strategy council and the members of the iSAQB^®^ working group "Expert Level" make a majority decision on whether or not a person meets one of the stated requirements.

iSAQB^®^ is able to actively invite luminaries to participate in a topic group and refund the cost.

The luminaries must work in the chosen topic group as well. Nobody gets a certification without active and successful work in a topic group.
====

// end::EN[]
