// tag::DE[]
==== Kriterien für neue Bewerber:innen

Das CPSA-Expert Level (CPSA-E) ist die höchste Qualifizierungsstufe des iSAQB und richtet sich an äußerst erfahrene Softwarearchitekt:innen. Die Anforderungen und Voraussetzungen sind entsprechend anspruchsvoll und fokussieren sich auf fundierte Erfahrung, tiefgehende Expertise sowie die Fähigkeit, neue Lösungswege zu entwickeln und die Community zu bereichern.

Bewerber:innen müssen folgende Kriterien erfüllen, um in einer Themenarbeitsgruppe mitarbeiten zu dürfen:

===== Wissen und Praxiserfahrung

Bewerber:innen begründen ihre Eignung für das Thema, indem sie ihr Wissen und ihre Praxiserfahrung zusammenfassen.

[cols="<3,<7a"]
|===
| Kriterium | Beschreibung

|Advanced Level
|Bewerber:innen müssen bestätigen, dass sie spätestens bis zur Einreichung der Expert-Level-Arbeit über das Advanced-Level-Zertifikat verfügen.

|Praxiserfahrung
|Bewerber:innen können mindestens 7 Jahre Berufserfahrung in der Rolle Softwarearchitekt in komplexen Softwareprojekten vorweisen. Dabei sind insbesondere Erfahrung in der system-, domänen- oder organisationsübergreifende Archiekturarbeit notwendig.

|Wissen
|Beherrschung und Praxisanwendung aller grundlegenden und fortgeschrittenen Konzepte der Softwarearchitektur, wie sie in den iSAQB-Lehrplänen für das Foundation- und Advanced-Level vermittelt werden.

|Wissensvermittlung und Community-Beitrag
|Nachweis über die Weitergabe von Wissen oder eines Community-Beitrag, beispielsweise durch die Schulung und Betreuung von weniger erfahrenen Entwickler:innen oder Architekt:innen, die fachliche Leitung von Architektur- oder Entwicklungsteams, Mitentwicklung in Open-Source-Projekten sowie durch Publikationen oder Vorträge.

|Kommunikative Fähigkeiten
|Bewerber:innen müssen in der Lage sein, komplexe Sachverhalte klar und verständlich zu kommunizieren.

|===

===== Organisation und Rahmenbedingungen

[cols="<3,<7a"]
|===
| Kriterium | Beschreibung

|iSAQB^®^ darf Ergebnisse veröffentlichen und verwerten
|Bewerber:innen müssen einwilligen, dass die Ergebnisse der Themenarbeitsgruppe von iSAQB^®^ veröffentlicht und verwertet werden dürfen.

|Reisebereitschaft
|Bewerber:innen müssen sich bereit erklären, für die Arbeit in der Themenarbeitsgruppe Reisen auf eigene Kosten zu unternehmen.

|Weitergabe von Kontaktdaten
|Bewerber:innen erteilen dem iSAQB^®^ die Berechtigung, folgende Daten an andere Mitglieder der Themenarbeitsgruppe weiterleiten zu dürfen: Vorname, Nachname, E-Mail-Adresse, Telefonnummer.

|===

==== Warum sind diese Voraussetzungen wichtig?

Das CPSA-Expert Level bescheinigt nicht nur technisches Wissen, sondern auch die Fähigkeit, als Vordenker:in und Leader:in in der Softwarearchitektur-Community zu agieren. Die Bewerber:innen müssen zeigen, dass sie über die reine Architekturarbeit hinaus zur Weiterentwicklung des Berufsstandes beitragen können und in der Lage sind, auch schwierige Herausforderungen in komplexen Umfeldern zu meistern.

[NOTE]
.Folgende Kriterien treten vielleicht in Zukunft in Kraft
====
Das iSAQB^®^ kann auch Personen ohne Advanced-Level-Zertifikat als Bewerber:innen für den Expert Level zulassen, wenn sie eine der folgenden Kriterien erfüllen:

- Personen, die als Koryphäe auf dem zu bearbeitenden Thema bekannt sind.
- iSAQB-Mitglieder, die auf Grund ihrer Aufgabe beim iSAQB^®^ die Advanced-Level-Prüfungsfragen (bzw. -aufgaben) kennen und daher die Advanced-Level-Zertifizierung nicht machen können.

Die Entscheidung, ob jemand die obigen Kriterien erfüllt, wird durch einen Mehrheitsbeschluss vom iSAQB Strategie-Council und den Mitgliedern der AG-EL gefällt.

Das iSAQB^®^ kann aktiv Koryphäen einladen, in einer Themenarbeitsgruppe mitzuarbeiten und kann ihnen dafür die Kosten erstatten.

Auch Koryphäen müssen in Themenarbeitsgruppen mitarbeiten. Ohne Mitarbeit in einer Themenarbeitsgruppe und einer erfolgreichen Zertifizierung erhält niemand das EL-Zertifikat.
====



// end::DE[]

// tag::EN[]
==== Criteria for New Applicants
To be eligible to participate in a topic group, applicants must satisfy the following criteria:


[cols="<3,<7a"]
|===
| Criterion | Description

|Advanced Level Certifications
|Applicants must confirm that they have the expert level certification, or they will get it until the topic group submits their results.

|Knowledge and practical experience
|Applicants must prove that they have knowledge and practical experience of the chosen topic.

|iSAQB^®^ can publish results
|Applicants must agree that iSAQB^®^ is allowed to publish and exploit the results of the topic group.

|Willingness to travel
|Applicants must confirm that they are willing to travel at their own expense to work together in the topic group.

|Disclosure of contact data
|The applicants grant permission to iSAQB^®^ to forward the following contact details to the other members of the topic groups: first name, second name, e-mail address, and telephone number.

|===

[NOTE]
.The following criteria may come into operation in the future
====
iSAQB® may accept individuals as candidates for the expert level if they meet one of the following requirement:

- People who are distinguished experts on the topic.
- Members of iSAQB^®^ who are not permitted to participate in the iSAQB^®^ Advanced Level Certification since they know the examination question.

The iSAQB^®^ strategy council and the members of the iSAQB^®^ working group "Expert Level" make a majority decision on whether or not a person meets one of the stated requirements.

iSAQB^®^ is able to actively invite luminaries to participate in a topic group and refund the cost.

The experts must work in the chosen topic group as well. Nobody gets a certification without active and successful work in a topic group.
====

// end::EN[]
